### ISSUE TITLE
[BUG] device_tracker entity does not auto-update

### ISSUE THREAD

**Issue by cap60552** [mandarons/ha-bouncie#11]
**Describe the bug**
When HA polls Bouncie it does not appear to be saving the updated current GPS location.  

**To Reproduce**
1. Begin a trip in bouncie, and move the vehicle.
2. Check the reported GPS latitude / Longitude in the device tracker, no changes will be present.

**Expected behavior**
Device tracker should contain the most recently reported GPS coordinates of the vehicle.

**Comment by mandarons** [comment]
Oops.. looks like similar issue as #6 . Looking into it...
