### ISSUE TITLE
[BUG] Bouncie Not Updating - Error Doing Job: Task Exception Was Never Retrieved

### ISSUE THREAD

**Issue by cmaglio** [mandarons/ha-bouncie#18]
**Describe the bug**
Error seen is in the title. This occurs on HA/integration start. It looks like the error might be related to a specific battery parameter. The "Car Battery" sensor is unavailable, and I am still not receiving updates on any Bouncie sensors after integration start.

**To Reproduce**

Start the integration.

**Screenshots**

![image](https://user-images.githubusercontent.com/37604281/211595180-5cd8579e-92df-44cd-8279-59029b2a021a.png)

![image](https://user-images.githubusercontent.com/37604281/211595909-accb0a1f-c399-4c1b-b2b1-5ba01960bd50.png)

**Configuration**
V0.2.2

**Comment by mandarons** [comment]
@cmaglio looks like something unique going on with your setup. My guess is bouncie server isn't reporting battery status or reporting in different place, for your device.

**Comment by mandarons** [comment]
For some reason, `battery` key is missing from the response. This is weird. Bouncie folks needs to fix this on their end. This is not aligned with their docs.bouncie.dev API documentation. 

I will fix this as to report 'Not available' for missing data. If/when Bouncie folks fix this, it will automatically show up the correct information.

**Comment by cmaglio** [comment]
Thanks @mandarons! Does Bouncie have a way to report this as an API error? Happy to do that for you, but you might have better information for them to be able to fix it faster.

It is very strange though... I can see the vehicle's battery voltage status in their app, so it must just be the API.

**Comment by cmaglio** [comment]
@mandarons Should I report this bug to Bouncie or have you already done that?

**Comment by mandarons** [comment]
@cmaglio I already did it earlier today. They might contact you though to get more details as it is specific to your device/account. You can share the sample data that I sent you in HA community PM.

**Comment by cmaglio** [comment]
Awesome, thank you! Sorry hadn't checked there yet.
