### ISSUE TITLE
[FEATURE] Consider Rounding Vehicle Speed Values

### ISSUE THREAD

**Issue by cmaglio** [mandarons/ha-bouncie#20]
I'm not reporting this as a bug because it's probably "as designed". However, you might want to consider rounding the Vehicle Speed sensor to the nearest whole unit or some less precise value.

![image](https://user-images.githubusercontent.com/37604281/212192476-203c0a0d-9442-444e-b4ab-f1d93774eb84.png)

I'm not sure if there would be any use case for anything more precise than the nearest whole unit (mph/kmh/etc).

If you think there is a use case for something more precise than the nearest whole unit, maybe rounding to 2 decimal places would be a good compromise and similar to how the "Speed" attribute reports on the "Device_Tracker" entity?

![image](https://user-images.githubusercontent.com/37604281/212194026-cedd9eb9-f517-411e-89f7-957bc8a03280.png)

However, the current sensor value is probably more than anyone needs to know and doesn't quite looks as clean as it could.

Just a suggestion, but feel free to close if you feel this is not necessary. Thanks again for your work on this!

**Comment by mandarons** [comment]
I agree. I actually rounded fuel value but didn't do this one.
