### ISSUE TITLE
[BUG] Log Warning - sensor.<vehicle>_car_speed is using native unit of measurement 'None'

### ISSUE THREAD

**Issue by cap60552** [mandarons/ha-bouncie#26]
**Describe the bug**
After upgrading to the current version ( 2.4.0 ) I am seeing the following error message in the log files:
```
Entity sensor.escape_car_speed (<class 'custom_components.bouncie.sensor.BouncieSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('speed') it is using; expected one of ['in/d', 'km/h', 'kn', 'mm/d', 'mm/h', 'mph', 'in/h', 'ft/s', 'm/s']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**To Reproduce**

# Install and configure Bouncie integration.
# View Home Assistant Logs.

**Expected behavior**
Warning message to not occur.  Plugin should provide the appropriate unit of measure.  If the measurement is not accessible via the API, allow for selection from the config workflow or default to "mph".

**Comment by mandarons** [comment]
What's your Home Assistant version?

**Comment by cap60552** [comment]
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Comment by mandarons** [comment]
HA is acting weird - when I set the `native_unit_of_measurement` to `mph` (one of the suggested), it is converting that value to `km/h`. Asking HA folks on Discord...

I am guessing you have your units system set to US imperial in HA configuration, correct?

**Comment by mandarons** [comment]
@cap60552: Please upgrade to 2.5.0 and see if that fixes the issue.

**Comment by tonygauderman** [comment]
> @cap60552: Please upgrade to 2.5.0 and see if that fixes the issue.

Upgrade just a matter of copying the new files over the old ones in the custom_components folder and restarting?

**Comment by mandarons** [comment]
Yeah. That should do it.

**Comment by cap60552** [comment]
Seems to have taken care of it!  Thank you again, as always!
