### ISSUE TITLE
[BUG] Only one Bouncie Device shows in the integration

### ISSUE THREAD

**Issue by omayhemo** [mandarons/ha-bouncie#3]
**Describe the bug**
Althought I have two authorized devices, only one of them is added to the integration .

**To Reproduce**
1. Signed up in the developer portal and followed the setup instructions, no special actions needed.

**Expected behavior**
I expected all of my devices (currently 2) to show up in the integration.

**Comment by mandarons** [comment]
@omayhemo : did it throw any error in Home Assistant logs?

**Comment by omayhemo** [comment]
Sorry, holidays.  Nevertheless, you definitely fixed it.  Thanks!
