### ISSUE TITLE
[BUG] Deprecated Constant - SOURCE_TYPE_GPS

### ISSUE THREAD

**Issue by cap60552** [mandarons/ha-bouncie#45]
**Describe the bug**

```
Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:205
Integration: Device tracker (documentation, issues)
First occurred: 8:03:03 PM (2 occurrences)
Last logged: 8:03:03 PM

SOURCE_TYPE_GPS was used from bouncie, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please create a bug report at https://github.com/mandarons/ha-bouncie/issues

```

**To Reproduce**

Upgrade to 2024.3

Check the logs after the Bounce integration has loaded.

**Expected behavior**
I would like to see the error gone, before 2025.1 so that Bounce will continue to work.

**Comment by mandarons** [comment]
Looks like I already fixed it. Please upgrade to 0.7.0

https://github.com/mandarons/ha-bouncie/releases/tag/0.7.0

**Comment by cap60552** [comment]
So you did... Sorry :-)   Looks like the change to the 0.0.x numbering confused HACS and it hadn't reported a new version.
