### ISSUE TITLE
[BUG] - Battery and Fuel Not Being Reported By Integration Sensors

### ISSUE THREAD

**Issue by TMarzullo** [mandarons/ha-bouncie#48]
**Describe the bug**
The sensor entities for battery and fuel do not appear to be populating. I can't tell if the data isn't coming in the poll response from Bouncie or if the data is present but not being parsed.

**To Reproduce**
This is a fresh install of this integration for me, so after setting up 3 of these devices, the relevant entities have never populated.

- Battery is always 'Not available' and displays as -1
- Fuel displays as -1

See screen shots below:

**Expected behavior**
If the data is being returned from the Bouncie server call, I would expect it to be in the relevant entities.

**Screenshots**
![image](https://github.com/user-attachments/assets/10be3167-130a-433a-b02d-725df3eb8a8a)
![image](https://github.com/user-attachments/assets/3c9e0971-0c0b-4121-8004-bbf538b2d825)

**Configuration**
Integration Version: 0.7.0
HA Core: Version 2024.7.4
HA OS: Version 12.4
Hardware: Home Assistant Blue / Hardkernel ODROID-N2/N2+

**Additional context**
None.

**Comment by finity69x2** [comment]
Also while we're here...
 
the device class for the fuel is showing as 'battery'. I'm not sure what it should be but it's definitely not a battery.
