### ISSUE TITLE
Integration Loads with Vehicle Data, But Data Does Not Get Updated/Refreshed

### ISSUE THREAD

**Issue by cmaglio** [mandarons/ha-bouncie#6]
**Describe the bug**
Integration appears to load okay and gets the data for the vehicle, but status updates do not appear to be happening after. I am seeing some errors in the logs. I assume these errors are related to this behavior. Screenshots of errors below.

**To Reproduce**
Start the integration.

**Expected behavior**
Integration would get regular updates to vehicle data. Bouncie claims 10sec updates?

**Screenshots**
![image](https://user-images.githubusercontent.com/37604281/210151479-96c9b90f-ca6e-414e-b918-716a8fea9f50.png)

![image](https://user-images.githubusercontent.com/37604281/210151492-51c6bea4-984a-4c87-9e65-8821c1a9fa78.png)

![image](https://user-images.githubusercontent.com/37604281/210151497-f1dffa19-3505-48b1-9baa-83b5285ad8c1.png)

**Configuration**
I have one Bouncie device on my account.

**Additional context**
Using the latest version of the custom integration : V 0.2.0

The below screenshot was taken 27 minutes after a HA restart while a trip was underway with the vehicle, the data is stale and not being updated. This happens for all sensors related to the integration.

![image](https://user-images.githubusercontent.com/37604281/210151791-b924f885-4d5a-4a71-a720-5769d2ed1c73.png)

Thanks again for your work on this integration!

**Comment by 29w211barnes** [comment]
I'm not seeing any errors, but I'm also not seeing any refreshes happening.

**Comment by mandarons** [comment]
Looking into it...

**Comment by 29w211barnes** [comment]
I finally figured out the debug logging and am seeing the following:
`Figured out the debug logging.  Looks like it is fetching the data, but not saving it to HA?
```
2023-01-03 23:08:33.536 DEBUG (MainThread) [custom_components.bouncie.const] Finished fetching bouncie data in 0.317 seconds (success: True)
2023-01-03 23:09:33.493 DEBUG (MainThread) [custom_components.bouncie.const] Finished fetching bouncie data in 0.275 seconds (success: True)
2023-01-03 23:10:33.482 DEBUG (MainThread) [custom_components.bouncie.const] Finished fetching bouncie data in 0.265 seconds (success: True)
2023-01-03 23:11:33.550 DEBUG (MainThread) [custom_components.bouncie.const] Finished fetching bouncie data in 0.327 seconds (success: True)
2023-01-03 23:12:33.517 DEBUG (MainThread) [custom_components.bouncie.const] Finished fetching bouncie data in 0.299 seconds (success: True)
2023-01-03 23:13:33.519 DEBUG (MainThread) [custom_components.bouncie.const] Finished fetching bouncie data in 0.300 seconds (success: True)
2023-01-03 23:14:33.573 DEBUG (MainThread) [custom_components.bouncie.const] Finished fetching bouncie data in 0.355 seconds (success: True)
```

So it looks like its fetching data, but not updating HA with the new data?

**Comment by mandarons** [comment]
@29w211barnes : Thank you very much for debugging the issue. I think, that is it.  I don't have a Bouncie device. I am waiting for new bouncie credentials from one of the forum members ([chintito4ever](https://community.home-assistant.io/u/chintito4ever)) to reproduce and fix it.

**Comment by 29w211barnes** [comment]
Let me know if you would like credentials for mine as well, I have two devices so that might be helpful with the multi-device code as well.

**Comment by mandarons** [comment]
That would be great. Please send me the details in HA community as a private message. Hopefully, we will be done with uncovering all the bugs and fixing them, soon.

**Comment by cmaglio** [comment]
Thanks @mandarons, if you cannot find the "KeyError: Battery" error by using others credentials, I'll be glad to give you access to my account as well so you can see that specific sensor error shown in the screenshots above.

**Comment by mandarons** [comment]
@cmaglio: sounds good.

**Comment by mandarons** [comment]
@cmaglio I was not able to reproduce the battery key error. Please try with version 0.2.1 and see if it fixes the problem. Please make sure to fully delete the integration and create a new one.

**Comment by cmaglio** [comment]
@mandarons Sorry, I had a CPU failure over the weekend... still trying to recover. I was able to give this a shot today and I still have a battery key error. I did delete the integration and start over. I guess I'll open a new issue.
