### ISSUE TITLE
[FEATURE] Metric support

### ISSUE THREAD

**Issue by mlewanca** [mandarons/ha-bouncie#7]
Could you add metric support?
I think it's miles and would need km.

Thanks!

**Comment by mandarons** [comment]
HA should automatically convert values to Metric equivalent if you have selected metric system in HA configuration. Is it not doing that?

**Comment by mlewanca** [comment]
Hello Mandar,

Thanks for getting back to me.

HA config is set to metric, but the entities are set to miles.


[image: image.png]

I just figured out that I can set it to km manually.

[image: image.png]

Consider this a no issue anymore.


Thanks again.

Regards,
Markus
